default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: 'fno2d'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # FNO related
  fno2d:
    data_channels: 3
    n_modes_height: 90
    n_modes_width: 90
    hidden_channels: 64
    projection_channels: 256
    n_layers: 4
    domain_padding: 0.078125
    domain_padding_mode: 'one-sided' #symmetric
    fft_norm: 'forward'
    norm: None
    skip: 'soft-gating'
    implementation: 'reconstructed'
    
    use_mlp: 1
    mlp_expansion: 0.5
    mlp_dropout: 0

    separable: False
    factorization: None
    rank: 1.0
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False
    fno_block_precision: 'full' # or 'half', 'mixed'
    stabilizer: None # or 'tanh'

  # Optimizer
  opt:
    n_epochs: 500
    learning_rate: 1e-3
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 60
    gamma: 0.5

  # Dataset related
  data:
    batch_size: 16
    n_train: 1000
    train_resolution: 16
    n_tests: [100, 50]
    test_resolutions: [16, 32]
    test_batch_sizes: [16, 16]
    positional_encoding: True

    encode_input: True
    encode_output: False

  # Patching
  patching:
    levels: 0
    padding: 0
    stitching: False
    
  incremental:
    incremental_loss_gap: False
    incremental_grad: False
    incremental_res: False
    grad_eps: 0.99999
    max_iter: 1
    loss_eps: 0.01
    grad_max: 2
    epoch_gap: 50

  galore: True
  scale: 0.25
  rank: 0.1
  
  # Weights and biases
  wandb:
    log: True
    name: "darcy-TFNO" # If None, config will be used but you can override it here
    group: '' 
    project: "darcy"
    entity: "research-pino_ifno" # put your username here
    sweep: False
    log_output: True
    log_test_interval: 1
