default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None #If None, will be computed
  verbose: True
  arch: 'fno2d'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # FNO related
  fno2d:
    data_channels: 3
    n_modes_height: 24
    n_modes_width: 24
    hidden_channels: 64
    projection_channels: 256
    n_layers: 4
    domain_padding: 0.078125
    domain_padding_mode: 'one-sided' #symmetric
    fft_norm: 'forward'
    norm: None
    skip: 'soft-gating'
    implementation: 'reconstructed'
    
    use_mlp: 1
    mlp_expansion: 0.5
    mlp_dropout: 0

    separable: False
    factorization: None
    rank: 1.0
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False
    fno_block_precision: 'full' # or 'half', 'mixed'
    stabilizer: None # or 'tanh'

  incremental:
    incremental_loss_gap: False
    incremental_grad: False
    incremental_res: False
    grad_eps: 0.9999
    max_iter: 1
    loss_eps: 0.1
    grad_max: 2
    epoch_gap: 100
    sub_list1: [4, 2, 1]
    
  # Optimizer
  opt:
    n_epochs: 500
    learning_rate: 1e-3
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 150
    gamma: 0.5

  # Dataset related
  data:
    # folder: '/home/nikola/HDD/NavierStokes/2D'
    folder: '/pscratch/sd/r/rgeorge/data/nsforcing_128.zip (Unzipped Files)/'
    # folder: '/data'
    batch_size: 16
    n_train: 10000
    train_resolution: 128
    n_tests: [2000, 1000, 1000] #, 1000]
    test_resolutions: [128, 256, 512] #, 1024] 
    test_batch_sizes: [16, 8, 4] #, 1]
    positional_encoding: True

    encode_input: False
    encode_output: False
    num_workers: 0
    pin_memory: False
    persistent_workers: False

  # Patching
  patching:
    levels: 0 #1
    padding: 0 #0.078125
    stitching: True

  # Weights and biases
  wandb:
    log: True
    name: "navierstokes-3d-final-rerun" # If None, config will be used but you can override it here
    group: '' 
    project: "navier-stokes"
    entity: "research-pino_ifno" # put your username here
    sweep: False
    log_output: True
    log_test_interval: 1

  seed: 0
  
original_fno:
  arch: 'tfno2d'

  fno2d:
    modes_height: 64
    modes_width: 64
    width: 64
    hidden_channels: 256
    n_layers: 4
    domain_padding: 0.078125
    domain_padding_mode: 'one-sided'
    fft_norm: 'forward'
    norm: None
    skip: 'linear'
    
    use_mlp: 0
    mlp:
        expansion: 0.5
        dropout: 0

    separable: False
    factorization: None
    rank: 1.0
    fixed_rank_modes: None
